# Generated by Django 5.2.7 on 2025-11-02 08:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavbarSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for identifying this navbar in the CMS (not shown on site).",
                        max_length=255,
                    ),
                ),
                (
                    "navbar",
                    wagtail.fields.StreamField(
                        [("Navbar", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter the foundation or organization name",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Upload the logo for the foundation or organization",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Text for the link", "required": True},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "URL for the link", "required": True},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("link_text", 2), ("link_url", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {"help_text": "Add Navigation links for the main menu"},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("brand_name", 0), ("logo", 1), ("links", 5)]],
                                {},
                            ),
                        },
                        help_text="Navigation bar details including logo, brand name, and links.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbar Snippet",
                "verbose_name_plural": "Navbar Snippets",
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="navbar_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which navigation bar snippet to display.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.navbarsnippet",
            ),
        ),
    ]
