# Generated by Django 5.2.7 on 2025-11-02 09:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_navbarsnippet_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navbarsnippet",
            name="navbar",
            field=wagtail.fields.StreamField(
                [("Navbar", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the foundation or organization name",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload the logo for the foundation or organization",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for the link", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the link", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 2), ("link_url", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {"help_text": "Add Navigation links for the main menu"},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Donate",
                            "help_text": "Text to display on the donation button.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/donate/",
                            "help_text": "URL for the donation button.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_name", 0),
                                ("logo", 1),
                                ("links", 5),
                                ("button", 6),
                                ("button_url", 7),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Navigation bar details including logo, brand name, and links.",
            ),
        ),
    ]
