# Generated by Django 5.2.7 on 2025-11-02 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_navbarsnippet_navbar"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaviconSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for identifying this favicon in the CMS (not shown on site).",
                        max_length=255,
                    ),
                ),
                (
                    "favicon",
                    wagtail.fields.StreamField(
                        [("Favicon", 1)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Upload the favicon for the website",
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("favicon", 0)]], {}),
                        },
                        help_text="Upload the favicon image for the browser tab icon.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favicon Snippet",
                "verbose_name_plural": "Favicon Snippets",
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="favicon_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which favicon snippet to display.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.faviconsnippet",
            ),
        ),
    ]
