# Generated by Django 5.2.7 on 2025-11-02 09:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_faviconsnippet_homepage_favicon_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faviconsnippet",
            name="favicon",
            field=wagtail.fields.StreamField(
                [("Favicon", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload a .ico or .png file for the favicon",
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("favicon", 0)]], {}),
                },
                help_text="Upload the favicon image for the browser tab icon.",
            ),
        ),
    ]
